import { Injectable } from '@angular/core';

export enum CssNamedColor {
  AliceBlue = 'aliceblue',
  AntiqueWhite = 'antiquewhite',
  Aqua = 'aqua',
  Aquamarine = 'aquamarine',
  Azure = 'azure',
  Beige = 'beige',
  Bisque = 'bisque',
  BlanchedAlmond = 'blanchedalmond',
  Blue = 'blue',
  BlueViolet = 'blueviolet',
  Brown = 'brown',
  BurlyWood = 'burlywood',
  CadetBlue = 'cadetblue',
  Chartreuse = 'chartreuse',
  Chocolate = 'chocolate',
  Coral = 'coral',
  CornflowerBlue = 'cornflowerblue',
  Cornsilk = 'cornsilk',
  Crimson = 'crimson',
  Cyan = 'cyan',
  DarkBlue = 'darkblue',
  DarkCyan = 'darkcyan',
  DarkGoldenRod = 'darkgoldenrod',
  DarkGray = 'darkgray',
  DarkGreen = 'darkgreen',
  DarkGrey = 'darkgrey',
  DarkKhaki = 'darkkhaki',
  DarkMagenta = 'darkmagenta',
  DarkOliveGreen = 'darkolivegreen',
  DarkOrange = 'darkorange',
  DarkOrchid = 'darkorchid',
  DarkRed = 'darkred',
  DarkSalmon = 'darksalmon',
  DarkSeaGreen = 'darkseagreen',
  DarkSlateBlue = 'darkslateblue',
  DarkSlateGray = 'darkslategray',
  DarkSlateGrey = 'darkslategrey',
  DarkTurquoise = 'darkturquoise',
  DarkViolet = 'darkviolet',
  DeepPink = 'deeppink',
  DeepSkyBlue = 'deepskyblue',
  DimGray = 'dimgray',
  DimGrey = 'dimgrey',
  DodgerBlue = 'dodgerblue',
  FireBrick = 'firebrick',
  FloralWhite = 'floralwhite',
  ForestGreen = 'forestgreen',
  Fuchsia = 'fuchsia',
  Gainsboro = 'gainsboro',
  GhostWhite = 'ghostwhite',
  Gold = 'gold',
  GoldenRod = 'goldenrod',
  Gray = 'gray',
  Green = 'green',
  GreenYellow = 'greenyellow',
  Grey = 'grey',
  HoneyDew = 'honeydew',
  HotPink = 'hotpink',
  IndianRed = 'indianred',
  Indigo = 'indigo',
  Ivory = 'ivory',
  Khaki = 'khaki',
  Lavender = 'lavender',
  LavenderBlush = 'lavenderblush',
  LawnGreen = 'lawngreen',
  LemonChiffon = 'lemonchiffon',
  LightBlue = 'lightblue',
  LightCoral = 'lightcoral',
  LightCyan = 'lightcyan',
  LightGoldenRodYellow = 'lightgoldenrodyellow',
  LightGray = 'lightgray',
  LightGreen = 'lightgreen',
  LightGrey = 'lightgrey',
  LightPink = 'lightpink',
  LightSalmon = 'lightsalmon',
  LightSeaGreen = 'lightseagreen',
  LightSkyBlue = 'lightskyblue',
  LightSlateGray = 'lightslategray',
  LightSlateGrey = 'lightslategrey',
  LightSteelBlue = 'lightsteelblue',
  LightYellow = 'lightyellow',
  Lime = 'lime',
  LimeGreen = 'limegreen',
  Linen = 'linen',
  Maroon = 'maroon',
  MediumAquaMarine = 'mediumaquamarine',
  MediumBlue = 'mediumblue',
  MediumOrchid = 'mediumorchid',
  MediumPurple = 'mediumpurple',
  MediumSeaGreen = 'mediumseagreen',
  MediumSlateBlue = 'mediumslateblue',
  MediumSpringGreen = 'mediumspringgreen',
  MediumTurquoise = 'mediumturquoise',
  MediumVioletRed = 'mediumvioletred',
  MidnightBlue = 'midnightblue',
  MintCream = 'mintcream',
  MistyRose = 'mistyrose',
  Moccasin = 'moccasin',
  NavajoWhite = 'navajowhite',
  Navy = 'navy',
  OldLace = 'oldlace',
  Olive = 'olive',
  OliveDrab = 'olivedrab',
  Orange = 'orange',
  OrangeRed = 'orangered',
  Orchid = 'orchid',
  PaleGoldenRod = 'palegoldenrod',
  PaleGreen = 'palegreen',
  PaleTurquoise = 'paleturquoise',
  PaleVioletRed = 'palevioletred',
  PapayaWhip = 'papayawhip',
  PeachPuff = 'peachpuff',
  Peru = 'peru',
  Pink = 'pink',
  Plum = 'plum',
  PowderBlue = 'powderblue',
  Purple = 'purple',
  RebeccaPurple = 'rebeccapurple',
  Red = 'red',
  RosyBrown = 'rosybrown',
  RoyalBlue = 'royalblue',
  SaddleBrown = 'saddlebrown',
  Salmon = 'salmon',
  SandyBrown = 'sandybrown',
  SeaGreen = 'seagreen',
  SeaShell = 'seashell',
  Sienna = 'sienna',
  Silver = 'silver',
  SkyBlue = 'skyblue',
  SlateBlue = 'slateblue',
  SlateGray = 'slategray',
  SlateGrey = 'slategrey',
  Snow = 'snow',
  SpringGreen = 'springgreen',
  SteelBlue = 'steelblue',
  Tan = 'tan',
  Teal = 'teal',
  Thistle = 'thistle',
  Tomato = 'tomato',
  Transparent = 'transparent',
  Turquoise = 'turquoise',
  Violet = 'violet',
  Wheat = 'wheat',
  White = 'white',
  WhiteSmoke = 'whitesmoke',
  Yellow = 'yellow',
  YellowGreen = 'yellowgreen',

  /**
   * Representa o valor calculado da propriedade `color`.
   * Também é uma palavra-chave válida em CSS.
   */
  CurrentColor = 'currentcolor',
}


@Injectable({
  providedIn: 'root'
})
export class ColorService {
  getRandomColor(): CssNamedColor {
    const colors = Object.values(CssNamedColor);
    const randomIndex = Math.floor(Math.random() * colors.length);
    return colors[randomIndex];
  }  
}
